#!/bin/bash

set -e
#load helper functions
source helper

h_before

#load dvm script
. ../../dvm.sh

VERSION=$(dvm ls-remote | sort -R | tail -n 1)

# Remove the stuff we're clobbering.
h remove_directory $VERSION

dvm install "$VERSION"
dvm use "$VERSION"
dvm deactivate "$VERSION"

out=1
if [ "$(command -v dart)" ]
then
  out=
fi

#after
h remove_directory "$VERSION"
h_after

[ $out ]
