#!/bin/bash
#Helpers function for tasting

h_before(){
  #save and unset some variables
  #for testing
  _PATH=$PATH
  export PATH='/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  if [ -d "$DVM_DIR" ]; then
    _DVM_DIR=$DVM_DIR
    export DVM_DIR=''
  fi
}

h_after(){
  export PATH=$_PATH
  if [ -z "$_DVM_DIR" ]; then
    export DVM_DIR=$_DVM_DIR
  fi
}
#vim:set filetype=sh

h() {

  case "$1" in
    "before" )
      h_before
      ;;
    "after" )
      h_after
      ;;
    "remove_directory" )
      if [ "$2" -a -d "../../$2" ]
      then
        rm -R "../../$2"
      fi
      ;;
  esac

}
