#!/bin/bash

set -e
#load helper functions
source helper

h_before

#load dvm script
. ../../dvm.sh

VERSION=$(dvm ls-remote | sort -R | tail -n 1)

# Remove the stuff we're clobbering.
h remove_directory "$VERSION"

dvm install "$VERSION"

out=
if [ -d ../../${VERSION} ]
then
  out=1
fi

#after
h remove_directory "$VERSION"
h_after

[ "$out" ]
