#!/bin/bash
# Problem in dart package
# Revision in file revision and file version is not equal

set -e

#before
if [ -d "$DVM_DIR" ]; then
  _DVM_DIR=$DVM_DIR
  export DVM_DIR=''
fi

#load dvm script
. ../../dvm.sh

revision=$(dvm ls-remote | sort -R | tail -n 1)

# Remove the stuff we're clobbering.
[ -e ../../r${revision} ] && rm -R ../../r${revision}

dvm install ${revision}

out=$(dvm run $revision --version)

#after
[ -e ../../r${revision} ] && rm -R ../../r${revision}
if [ -z "$_DVM_DIR" ]; then
  export DVM_DIR=$_DVM_DIR
fi

echo "$out" | grep $revision
