#!/bin/bash

set -e
#load helper functions
source helper

h_before

#load dvm script
. ../../dvm.sh

echo "v0.1.2" > ../../alias/test
dvm unalias test

out=1

if [ -f ../../alias/test ]
then
  out=
fi

h_after

[ "$out" ]
